In [1]:
# Install the torch package
%pip install torch

import torch
import numpy as np


[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.


In [2]:
!pip list

Package                      Version
---------------------------- -----------
absl-py                      2.1.0
accelerate                   0.34.0
aiohappyeyeballs             2.3.4
aiohttp                      3.10.0
aiohttp-cors                 0.7.0
aiosignal                    1.3.1
altair                       5.3.0
annotated-types              0.7.0
anyio                        4.4.0
asttokens                    2.4.1
astunparse                   1.6.3
attrs                        23.2.0
azure-core                   1.30.2
azure-storage-blob           12.22.0
backoff                      2.2.1
beautifulsoup4               4.12.3
bitsandbytes                 0.43.3
blinker                      1.8.2
cachetools                   5.4.0
caer                         2.0.8
certifi                      2024.7.4
cffi                         1.17.0
chardet                      5.2.0
charset-normalizer           3.3.2
click                        8.1.7
cloudpickle                  3.0.0


# **TENSORS**

*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

*   Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

*  default data type of float32.

* More suitable for deep learning than a numpy array.


#List

In [3]:
nums = [1, 2 , 3, 4, 5]
nums

[1, 2, 3, 4, 5]

In [4]:
nums_2d = [[1, 2 , 3], [4, 5, 6]]
nums_2d

[[1, 2, 3], [4, 5, 6]]

#Numpy Array

In [5]:
np0 = np.random.rand(3)
np0

array([0.93111767, 0.10888026, 0.78546195])

In [6]:
np1 = np.random.rand(3, 4)
np1

array([[0.09955311, 0.36951752, 0.24933583, 0.57818255],
       [0.63005465, 0.80282362, 0.27768128, 0.9136305 ],
       [0.14172271, 0.14002918, 0.96036953, 0.02217018]])

In [9]:
np1.dtype

dtype('float64')

#Tensor

In [10]:
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[ 0.1304,  0.6063, -2.0262, -2.1819],
        [ 0.1962, -0.7091, -0.5967,  0.4604],
        [ 0.6127, -1.6058,  1.5230, -0.2383]])

In [11]:
tensor_2d.dtype

torch.float32

In [13]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [14]:
#create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0996, 0.3695, 0.2493, 0.5782],
        [0.6301, 0.8028, 0.2777, 0.9136],
        [0.1417, 0.1400, 0.9604, 0.0222]], dtype=torch.float64)

In [15]:
my_tensor2 = torch.arange(10)
my_tensor2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# Reshape and View
my_tensor3 = my_tensor2.reshape(2, 5) #(2, 6) not valid as 2*6 = 12 > 10
my_tensor3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
my_tensor4 = torch.arange(15)
my_tensor4

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
#-1 for auto correct dimention: here (2, -1) is not valid
my_tensor4 = my_tensor4.reshape(3, -1)
my_tensor4

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [19]:
my_tensor4 = my_tensor4.reshape(-1, 3)
my_tensor4

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [20]:
# view do the same thing
my_tensor_a = torch.arange(10)
my_tensor_a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
my_tensor_b = my_tensor_a.view(2, 5)
my_tensor_b

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [22]:
my_tensor_a[1] = 444
my_tensor_a

tensor([  0, 444,   2,   3,   4,   5,   6,   7,   8,   9])

In [23]:
#change update automatically
my_tensor_b

tensor([[  0, 444,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [24]:
# Slice
my_tensor_c = torch.arange(10)
my_tensor_c

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
my_tensor_c[7]

tensor(7)

In [26]:
my_tensor_d = my_tensor_c.reshape(5, 2)
my_tensor_d

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [27]:
my_tensor_d[:, 1]

tensor([1, 3, 5, 7, 9])

In [28]:
my_tensor_d[:, 1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

##L-4: Math

In [29]:
tensor_x = torch.tensor([1, 2, 3, 4])
tensor_y = torch.tensor([5, 6, 7, 8])

In [31]:
#Addition
tensor_x + tensor_y

tensor([ 6,  8, 10, 12])

In [32]:
#Addition Longhand
torch.add(tensor_x, tensor_y)

tensor([ 6,  8, 10, 12])

In [34]:
#Subtraction
tensor_x - tensor_y

tensor([-4, -4, -4, -4])

In [36]:
#Subtraction Longhand
torch.sub(tensor_x, tensor_y)

tensor([-4, -4, -4, -4])

In [37]:
#Multiplication
tensor_x * tensor_y

tensor([ 5, 12, 21, 32])

In [38]:
#Multiplication Longhand
torch.mul(tensor_x, tensor_y)

tensor([ 5, 12, 21, 32])

In [39]:
#Division
tensor_y / tensor_x

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [40]:
#Multiplication Longhand
torch.div(tensor_y, tensor_x)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [42]:
#Remainder
tensor_y % tensor_x

tensor([0, 0, 1, 0])

In [43]:
#Remainder Longhand
torch.remainder(tensor_y, tensor_x)

tensor([0, 0, 1, 0])

In [45]:
# Exponents / Power
tensor_y ** tensor_x

tensor([   5,   36,  343, 4096])

In [46]:
# Exponents / Power Longhand
torch.pow(tensor_y, tensor_x)

tensor([   5,   36,  343, 4096])

In [48]:
# Another way to write longhand
tensor_x.add(tensor_y)

# same works for sub, mul, div, remainder, pow

tensor([ 6,  8, 10, 12])

In [49]:
tensor_x += tensor_y
tensor_x

tensor([ 6,  8, 10, 12])

In [61]:
tensor_x = torch.tensor([1, 2, 3, 4])

In [62]:
tensor_x.add_(tensor_y)
tensor_x

tensor([ 6,  8, 10, 12])