In [12]:
import numpy as np

a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [4]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [5]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [6]:
for x in np.nditer(a, order="C"): #C: C order
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [13]:
for x in np.nditer(a, order="F"): #F: Fortran order
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [14]:
for x in np.nditer(a, order="F", flags=["external_loop"]): #F: Fortran order
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [15]:
for x in np.nditer(a, op_flags=["readwrite"]):
    x[...]=x*x
    
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [16]:
b = np.arange(3, 15, 4).reshape(3, 1)

b

array([[ 3],
       [ 7],
       [11]])

In [17]:
for x, y in np.nditer([a, b]): 
    print(x, y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


In [19]:
c = np.arange(3, 17, 4).reshape(4, 1)

c

array([[ 3],
       [ 7],
       [11],
       [15]])

In [20]:
for x, y in np.nditer([a, c]): #Invalide
    print(x, y)

ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 