In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import os 

In [ ]:
dataset_path = os.listdir('data/room_dataset')
room_types = os.listdir('data/room_dataset')

print(room_types)
print("Types of room found: ", len(room_types), "\n")


rooms = []

for item in room_types:                #bed_room/dining_room/living_room
    all_rooms = os.listdir('data/room_dataset/' + item)

    for room in all_rooms:
                # room type,                                     image path
        rooms.append((item, str('data/room_dataset/' + item) + '/' + room))
        print(rooms[-1]) 

['bed_room', 'dining_room', 'living_room']
Types of room found:  3 

('bed_room', 'data/room_dataset/bed_room/bed-1303451__340.jpg')
('bed_room', 'data/room_dataset/bed_room/bed-1846251__340.jpg')
('bed_room', 'data/room_dataset/bed_room/bed-3786264__340.jpg')
('bed_room', 'data/room_dataset/bed_room/bed-4065946__340.jpg')
('bed_room', 'data/room_dataset/bed_room/bed-4343379__340.jpg')
('bed_room', 'data/room_dataset/bed_room/bed-4343382__340.jpg')
('bed_room', 'data/room_dataset/bed_room/bed-4540208__340.jpg')
('bed_room', 'data/room_dataset/bed_room/bedroom-3102376__340.jpg')
('bed_room', 'data/room_dataset/bed_room/bedroom-374982__340.jpg')
('bed_room', 'data/room_dataset/bed_room/bedroom-4072391__340 (1).jpg')
('bed_room', 'data/room_dataset/bed_room/bedroom-460762__340.jpg')
('bed_room', 'data/room_dataset/bed_room/bedroom-690129__340.jpg')
('dining_room', 'data/room_dataset/dining_room/apartment-185778__340.jpg')
('dining_room', 'data/room_dataset/dining_room/apartment-185779__34

In [8]:
rooms_df = pd.DataFrame(rooms, columns=['room_type', 'image_path'])
print(rooms_df.head())

  room_type                                       image_path
0  bed_room  data/room_dataset/bed_room/bed-1303451__340.jpg
1  bed_room  data/room_dataset/bed_room/bed-1846251__340.jpg
2  bed_room  data/room_dataset/bed_room/bed-3786264__340.jpg
3  bed_room  data/room_dataset/bed_room/bed-4065946__340.jpg
4  bed_room  data/room_dataset/bed_room/bed-4343379__340.jpg


In [9]:
print("Total number of rooms: ", len(rooms_df))

Total number of rooms:  47


In [11]:
room_count = rooms_df['room_type'].value_counts()
print("Rooms in each catagory: ")
print(room_count)

Rooms in each catagory: 
room_type
living_room    24
bed_room       12
dining_room    11
Name: count, dtype: int64


In [12]:
import cv2 
path = 'data/room_dataset'

images = []
labels = []

for room in room_types:
    data_path = path + '/' + room

    file_names = [file for file in os.listdir(data_path)]

    for file in file_names:
        img_path = data_path + '/' + file
        img = cv2.imread(img_path) # Read the image as array
        img = cv2.resize(img, (60, 60)) # Resize the image to 60x60 pixels
        images.append(img)
        labels.append(room)

In [13]:
# Transform the image list to numpy array
images = np.array(images)
images.shape

(47, 60, 60, 3)

In [14]:
images = images / 255.0  # Normalize the images to [0, 1] range
images.shape

(47, 60, 60, 3)

In [17]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder 
y = rooms_df['room_type'].values
print(y[:5])

['bed_room' 'bed_room' 'bed_room' 'bed_room' 'bed_room']


In [21]:
y_label_encoder = LabelEncoder()
y = y_label_encoder.fit_transform(y)  # Encode the labels to integers
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2]


c:\Users\shahs_snohmej\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [26]:
y = y.reshape(-1, 1)  # Reshape to 2D array for OneHotEncoder
onehot_encoder = OneHotEncoder(sparse_output=False)
Y = onehot_encoder.fit_transform(y) # One-hot encode the labels
print(Y.shape)
print(Y)

(47, 3)
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [28]:
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

images, Y = shuffle(images, Y, random_state=42)

X_train, X_test, y_train, y_test = train_test_split(images, Y, test_size=0.1, random_state=42)

print("Training data shape: ", X_train.shape, y_train.shape)
print("Testing data shape: ", X_test.shape, y_test.shape)


Training data shape:  (42, 60, 60, 3) (42, 3)
Testing data shape:  (5, 60, 60, 3) (5, 3)


In [ ]:
import tensorflow as tf

num_classes = Y.shape[1]  # Number of unique room types

n_inputs = X_train.shape[1] * X_train.shape[2] * X_train.shape[3]  # Flatten the input images
print("Number of inputs: ", n_inputs)

Number of inputs:  10800


In [32]:
# Architecture hyperparameters
learing_rate = 0.001
batch_size = 32
epochs = 10
display_step = 20

In [34]:
img_size = X_train.shape[1]
n_channels = X_train.shape[3]  # Number of channels in the images (3 for RGB)
# x = tf.placeholder(tf.float32, [None, img_size, img_size, n_channels])

# y_ = tf.placeholder(tf.float32, [None, num_classes])

# print("Shape of placeholder", x.shape, y_.shape)

In [ ]:
def conv2d(x, W, b, strides=1):
    x = tf.nn.conv2d(x, W, strides=[1, strides, strides, 1], padding='SAME') # y = wx + b
    x = tf.nn.bias_add(x, b) # Add bias(b)
    return tf.nn.relu(x) # Apply ReLU activation function

def maxpool2d(x, k=2):      # windwow size = k(2)       strides = k(2)
    return tf.nn.max_pool2d(x, ksize=[1, k, k, 1], strides=[1, k, k, 1], padding='SAME')

In [39]:
weights = {               # 5X5 filter size, 32 filters for first layer, 64 for second layer, etc.
    'w1': tf.Variable(tf.random.truncated_normal([5, 5, n_channels, 32]), name='w1'),
                        # Here in 2nd layer, 32 means 32 filtered images generated, 64 for next layer, etc.
    'w2': tf.Variable(tf.random.truncated_normal([5, 5, 32, 64]), name='w2'),
    'w3': tf.Variable(tf.random.truncated_normal([5, 5, 64, 128]), name='w3'), 
    'wd1': tf.Variable(tf.random.truncated_normal([8 * 8 * 128, 2048]), name='wd1'), # Flattened size after conv layers
    # 2048 is the number of neurons in the fully connected layer
    'wout': tf.Variable(tf.random.truncated_normal([2048, num_classes]), name='wout')
}

biases = {
    'b1': tf.Variable(tf.random.truncated_normal([32]), name='b1'),
    # Here, 32 means bias for 32 filters in the first layer, 64 for second layer, etc.
    'b2': tf.Variable(tf.random.truncated_normal([64]), name='b2'),
    'b3': tf.Variable(tf.random.truncated_normal([128]), name='b3'),
    'bd1': tf.Variable(tf.random.truncated_normal([2048]), name='bd1'),
    'bout': tf.Variable(tf.random.truncated_normal([num_classes]), name='bout')
}

In [ ]:
# weights = {
#     'conv1': tf.Variable(tf.random.truncated_normal([5, 5, n_channels, 32], stddev=0.1), name='conv1'),
#     'conv2': tf.Variable(tf.random.truncated_normal([5, 5, 32, 64], stddev=0.1), name='conv2'),
#     'conv3': tf.Variable(tf.random.truncated_normal([5, 5, 64, 128], stddev=0.1), name='conv3'),
#     'fc1': tf.Variable(tf.random.truncated_normal([8 * 8 * 128, 2048], stddev=0.1), name='fc1'),
#     'out': tf.Variable(tf.random.truncated_normal([2048, num_classes], stddev=0.1), name='out')
# }       

# biases = {
#     'conv1': tf.Variable(tf.random.truncated_normal([32], stddev=0.1), name='conv1'),
#     'conv2': tf.Variable(tf.random.truncated_normal([64], stddev=0.1), name='conv2'),
#     'conv3': tf.Variable(tf.random.truncated_normal([128], stddev=0.1), name='conv3'),     
#     'fc1': tf.Variable(tf.random.truncated_normal([2048], stddev=0.1), name='fc1'),
#     'out': tf.Variable(tf.random.truncated_normal([num_classes], stddev=0.1), name='out')
# }

7

In [40]:
def conv_net(x, weights, biases):
    # Reshape input to 4D tensor: [batch_size, height, width, channels]
    x = tf.reshape(x, shape=[-1, img_size, img_size, n_channels])

    print("Shape of input tensor: ", x.shape) #60x60x3

    # Convolutional & Pooling Layer 1
    conv1 = conv2d(x, weights['w1'], biases['b1'])
    conv1 = maxpool2d(conv1, k=2)

    print("Shape after conv1: ", conv1.shape) #30x30x32


    # Convolutional & Pooling Layer 2
    conv2 = conv2d(conv1, weights['w2'], biases['b2'])
    conv2 = maxpool2d(conv2, k=2)

    print("Shape after conv2: ", conv2.shape) #15x15x64
    

    # Convolutional & Pooling Layer 3
    conv3 = conv2d(conv2, weights['w3'], biases['b3'])
    conv3 = maxpool2d(conv3, k=2)

    print("Shape after conv3: ", conv3.shape) #8x8x128


    # Fully Connected Layer
    # Reshape conv3 output to fit fully connected layer input 8x8x128 = 8192
    fc1 = tf.reshape(conv3, [-1, weights['wd1'].get_shape().as_list()[0]]) # Flatten the output
    print("Shape after flattening: ", fc1.shape) #8192

    # Fully connected layer with ReLU activation
    fc1 = tf.add(tf.matmul(fc1, weights['wd1']), biases['bd1'])
    fc1 = tf.nn.relu(fc1)
    print("Shape after fc1: ", fc1.shape) #2048

    # Output Layer
    out = tf.add(tf.matmul(fc1, weights['wout']), biases['bout'])
    print("Shape of output layer: ", out.shape) #num_classes
    
    return out

In [42]:
# Create the model 
model = conv_net(x, weights, biases)
print(model)

NameError: name 'x' is not defined

In [ ]:
# Define loss and optimizer
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=model, labels=y_))
optimizer = tf.train.AdamOptimizer(learning_rate=learing_rate).minimize(loss)

In [46]:
# initialize variables
# init = tf.global_variables_initializer() 
## No need to initialize variables in TensorFlow 2.x, as it uses eager execution by default.

In [ ]:
cost_history = []
epochs = 10

# the execution 
sess = tf.Session()
sess.run(init)

y_train = y_train.todense()  # Convert sparse matrix to dense format

for epoch in range(epochs):
    a, c = sess.run([optimizer, loss], feed_dict={x: X_train, y_: y_train})
    cost_history.append(c)
    print(f'Epoch {epoch + 1}, Loss: {c:.4f}')

In [ ]:
# Test the model
y_test = y_test.todense()  # Convert sparse matrix to dense format
correct_prediction = tf.equal(tf.argmax(model, 1), tf.argmax(y_, 1))
print(correct_prediction)

accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print(accuracy)

# Calculate accuracy on test data
test_accuracy = sess.run(accuracy, feed_dict={x: X_test, y_: y_test})
print(f'Test Accuracy: {test_accuracy:.4f}')