In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("E:\Programming\AI\ML Files\AI ML\ML - Codebasics\homeprices3.csv")
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [4]:
import math
median_bedrooms = math.floor(df.bedroom.median())
median_bedrooms

3

In [5]:
df.bedroom = df.bedroom.fillna(median_bedrooms)
df

area  bedroom  age   price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [8]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedroom', 'age']], df.price)

reg.coef_ #m1      m2          m3

array([   137.25, -26025.  ,  -6825.  ])

In [9]:
reg.intercept_ #c

383724.9999999998

In [11]:
          #area bedroom age
reg.predict([[3000, 3, 40]])
#y = max+c
#price = m1*area + m2*bedroom + m3*age + c

C:\Users\shahs_snohmej\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [14]:
137.25*3000 + -26025*3 + -6825*40 + 383724.9999999998

444399.9999999998

In [12]:
reg.predict([[3000, 3, 15]])

C:\Users\shahs_snohmej\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([615025.])

In [15]:
reg.predict([[2500, 4, 5]])

C:\Users\shahs_snohmej\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])