In [2]:
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]])

a.ndim

2

In [3]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
a.itemsize #byte size of each element

4

In [8]:
b = np.array([[1, 2], [3, 4], [5, 6]], dtype = np.float64)
b.itemsize

8

In [9]:
b

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [10]:
a.size

6

In [11]:
a.shape

(3, 2)

In [15]:
c = np.array([[1, 2], [3, 4], [5, 6]], dtype = complex)
c.itemsize

16

In [22]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [17]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
l = range(5) #array of 5 element (val: 0-4)
l

range(0, 5)

In [20]:
l[1]

1

In [21]:
l[0]

0

In [26]:
l[4]

4

In [25]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [27]:
     #start end increment
np.arange(1, 5, 2)

array([1, 3])

In [28]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [30]:
a = np.array([[1, 2], [3, 4], [5, 6]])

a.shape

(3, 2)

In [31]:
a.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [33]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [34]:
a.min()

1

In [35]:
a.max()

6

In [36]:
a.sum()

21

In [37]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
a.sum(axis=0)

array([ 9, 12])

In [39]:
a.sum(axis=1)

array([ 3,  7, 11])

In [40]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [41]:
np.std(a) #standard deviation

1.707825127659933

In [44]:
x = np.array([[1, 2], [3, 4]])

x

array([[1, 2],
       [3, 4]])

In [43]:
y = np.array([[5, 6], [7, 8]])

y

array([[5, 6],
       [7, 8]])

In [46]:
x+y

array([[ 6,  8],
       [10, 12]])

In [47]:
x/y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [49]:
x.dot(y) #matrix dot multiplication

array([[19, 22],
       [43, 50]])